#!/bin/sh

# Get memory usage
MEM_INFO=$(free -m | awk 'NR==2{printf "%.1f/%.1fG (%.0f%%)", $3/1024, $2/1024, $3*100/$2 }')

echo "$MEM_INFO"
echo "$MEM_INFO"

# Color based on usage
USAGE_PERCENT=$(free | awk 'NR==2{printf "%.0f", $3*100/$2}')
if [ $USAGE_PERCENT -lt 50 ]; then
    echo "#00FF00"
elif [ $USAGE_PERCENT -lt 80 ]; then
    echo "#FFA500"
else
    echo "#FF0000"
fi
